# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: echo hello
          command:
            echo Hello
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: echo world
          command:
            echo world
  print-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: echo world
          command:
            echo $OWNER_NAME
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: echo world
          command:
            echo "text to output here" > output.txt
      - persist_to_workspace:
        root: /tmp/
        path:
          - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/output.txt
      - run:
          name: echo world
          command:
            cat output.txt
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print-hello
      - print-world:
          requires: [print-hello]
      - print-name:
          requires:
            - print-world
      - save_hello_world_output
